server:
  port: 8080

spring:
  application:
    name: orderservice
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.215:3306/vcloud_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=Hongkong&allowMultiQueries=true
      username: root
      password: 123456
  #  redis:
  #    host: 192.168.1.215
  #    port: 6379
  #    password: dgbigdata123
  #    database: 5
  #    jedis:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 1
  #        time-between-eviction-runs: 10s
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 2MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  cloud:
    nacos:
      server-addr: localhost:8848
#      discovery:
#        cluster-name: HZ
#        namespace: b524226d-e59f-48b8-8bf0-be44f0ac405a

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      logic-delete-field: delFlag
      #      logic-delete-value: 1
      #      logic-not-delete-value: 0
      id-type: auto

#七牛云外链文件地址
#qiniu:
#  path: http://rrg5r2yt5.hn-bkt.clouddn.com/

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

logging:
  level:
    com:
      tony: debug

